---
name: amigos
description: A Social Media Application
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  connectivity: ^0.4.9
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  animations: ^1.1.2
  image_picker: ^0.6.7+4
  device_preview: ^0.4.7
  shared_preferences: ^0.5.8
  cached_network_image: ^2.2.0+1
  toast: ^0.1.5
  flutter_chip_tags: ^1.0.3
  random_color: ^1.0.5
  swipedetector: ^1.2.0
  photo_view: ^0.9.2
  timeago: ^2.0.26
  flutter_share: ^1.0.2+1
flutter:
  uses-material-design: true
  assets:
  - assets/images/intro_simgle.gif
  - assets/images/small_logo.png
  - assets/images/small_logo_loading.gif
  - assets/images/splash.gif
