---
name: amigos
description: A Social Media Application
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.0
  connectivity: ^3.0.2
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  animations: ^2.0.0
  image_picker: ^0.7.2+1
  shared_preferences: ^2.0.4
  cached_network_image: ^2.5.1
  toast: ^0.1.5
  flutter_chip_tags: ^1.0.4
  random_color: ^1.0.5
  swipedetector: ^1.2.0
  photo_view: ^0.11.1
  timeago: ^3.0.2
  flutter_share: ^1.0.5
  firebase_dynamic_links: ^0.8.0
  firebase_analytics: ^7.1.1
  flutter_share_me: ^0.9.2
  font_awesome_flutter: ^8.12.0
  flutter_cache_manager: ^2.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/intro_simgle.gif
    - assets/images/small_logo.png
    - assets/images/small_logo_loading.gif
    - assets/images/splash.gif
