/// Generated by AssetsRefGenerator on 2020/08/02
class Res {
  static const String intro_simgle = "assets/images/intro_simgle.gif";
  static const String small_logo = "assets/images/small_logo.png";
  static const String small_logo_loading = "assets/images/small_logo_loading.gif";
  static const String splash = "assets/images/splash.gif";
}
